// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SharedLoading: typeof import('C:/Work/portfolio-clone/src/components/shared/Loading.vue')['default']
    SharedSoundButton: typeof import('C:/Work/portfolio-clone/src/components/shared/SoundButton.vue')['default']
  }
}

export { }
